default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: meal_on_the_fence_observer

test:
  <<: *default
  database: meal_on_the_fence_observer

production:
  <<: *default
  database: meal_on_the_fence_observer
