# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da5c9265fa361706d577e1a6427687f2fa26140d99d9defa75f1b448987f2b74a8a3e58466be4744f5d5e452c88cf5d6806874d12d726565281c29d6473d96e2
  FACEBOOK_APP_ID: "772755333546667"
  FACEBOOK_APP_SECRET: "4162ff819591cdb9b7526e32e1a19c3b"
  TWITTER_APP_ID: "6TvfIIEbuBgnLaRM6EWcodDv5"
  TWITTER_APP_SECRET: "2psgZHCbZQHCk7W7Dl8q4XQ0Y1lYc72a4JQ0OT5RIlzZkkgvq8"
  WEBHOOK_URL: "https://hooks.slack.com/services/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"

test:
  secret_key_base: bc91d9cd6b900dc25e15aae76be1c6f2a3ef6907994a30aa9acaa6f219c9db7a1e0ef3035b8ebbd17a13d96e3aec4f0b0445e77e1be0bbe4d2befcfaf75b0f36
  FACEBOOK_APP_ID: "772755333546667"
  FACEBOOK_APP_SECRET: "4162ff819591cdb9b7526e32e1a19c3b"
  TWITTER_APP_ID: "6TvfIIEbuBgnLaRM6EWcodDv5"
  TWITTER_APP_SECRET: "2psgZHCbZQHCk7W7Dl8q4XQ0Y1lYc72a4JQ0OT5RIlzZkkgvq8"
  WEBHOOK_URL: "https://hooks.slack.com/services/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"
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_APP_ID: <%= ENV["FACEBOOK_APP_ID"] %>
  FACEBOOK_APP_SECRET: <%= ENV["FACEBOOK_APP_SECRET"] %>
  TWITTER_APP_ID: <%= ENV["TWITTER_APP_ID"] %>
  TWITTER_APP_SECRET: <%= ENV["TWITTER_APP_SECRET"] %>
  WEBHOOK_URL: <%= ENV["WEBHOOK_URL"] %>
